<a href="https://colab.research.google.com/github/Ant2965/100Days_Challenge/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [73]:
list1 =[1,2,3,4,5]
print (list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [74]:
import numpy as jh


In [75]:
p_array = p.array([1,2,3,4,4,5,5,5])
print(np_array)
type(np_array)

[1 2 3 4 4 5 5 5]


numpy.ndarray

In [76]:
a= np.array([1,2,3,4,5])
print(a)
a.shape

[1 2 3 4 5]


(5,)

In [77]:
b=np.array([(1,2,3,4,5),(2,5,45,45,45)])
print(b)
b.shape

[[ 1  2  3  4  5]
 [ 2  5 45 45 45]]


(2, 5)

In [78]:
c=np.array([(1,2,3,4),(4,5,67,7)])
print(c)

[[ 1  2  3  4]
 [ 4  5 67  7]]


Placeholders

In [79]:
# create a numpy array of zeroes

x =np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [80]:
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [81]:
z=np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [82]:
a=np.eye(7)
print(a)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [83]:
b=np.random.random((3,4))
print(b)

[[0.8811955  0.51836714 0.85310621 0.59079137]
 [0.17037444 0.26371452 0.3083373  0.66296074]
 [0.09782999 0.48997896 0.73593936 0.61621305]]


In [84]:
c=np.random.randint(10,100,(10,7))
print(c)

[[63 69 15 73 30 43 65]
 [41 79 12 82 96 82 26]
 [85 12 28 62 37 22 43]
 [29 14 83 94 50 83 68]
 [90 10 56 83 95 42 39]
 [59 23 15 58 39 52 81]
 [97 45 68 18 78 97 81]
 [43 79 70 75 22 34 46]
 [86 58 74 20 14 74 42]
 [85 59 28 39 99 51 62]]


In [85]:
d =np.linspace(10,40,4)
print(d)

[10. 20. 30. 40.]


In [90]:
e=np.arange(10,30,10)
print(e)

[10 20]


In [91]:
#conversion list to numpy

list2= [2,3,4,54,4,6,4]
np_array=np.asarray(list2)
print(np_array)
type(np_array)

[ 2  3  4 54  4  6  4]


numpy.ndarray

Analyse

In [93]:
c=np.random.randint(10,90,(5,5))
print(c)

[[73 85 49 72 49]
 [72 85 43 11 87]
 [84 35 25 30 46]
 [61 44 88 23 23]
 [80 84 83 87 30]]


In [94]:
print(c.shape)

(5, 5)


In [96]:
print(c.ndim)
print(c.dtype)

2
int64


In [97]:
list1=[1,2,3,4,5]
list2=[1,2,3,4,5]
print(list1+list2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [101]:
a= np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a+b)
print(a*b)

[[17 12 12]
 [21 20 20]
 [14 19 17]]
[[70 20  0]
 [54 51 51]
 [13 88 16]]


In [102]:
a=np.random.randint(0,20,(2,3))
print(a)
print(a.shape)

[[ 7 12 17]
 [ 3  5  5]]
(2, 3)


In [103]:
b=a.reshape(3,2)
print(b)
print(b.shape)

[[ 7 12]
 [17  3]
 [ 5  5]]
(3, 2)
